[package]
name = "nerd-helper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nerd-core = { path = "../nerd-core" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[lints]
workspace = true
